<a href="https://colab.research.google.com/github/kennedy1907big/aula_analise-de-dados/blob/main/Conhe%C3%A7a_o_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
import pandas as pd
drive.mount( '/content/drive')
df = pd.read_csv ('/content/drive/MyDrive/dados/dados1.csv')
print(df)

Mounted at /content/drive
    Unnamed: 0        nome  idade  salário
0          NaN  Paçoquinha     20   1500.0
1          NaN      Paçoca     20   2200.0
2          NaN   Paçoquita     20  10000.0
3          NaN     Bolacha     20   5500.0
4          NaN        Enzo     20   2100.0
5          NaN         Ana     20   2100.0
6          NaN       Laura     20   2100.0
7          NaN     Isadora     20   2100.0
8          NaN        Tony     20   2100.0
9          NaN       Steve     20   2100.0
10         NaN      Fulano     20   2100.0
11         NaN     Ciclano     20      NaN
12         NaN  Totezuando     20   2100.0
13         NaN   Mussarelo     20   2100.0
14         NaN     Claudio     20   2100.0
15         NaN       Julia     20   2100.0
16         NaN       Henry     20   2100.0
17         NaN       Harry     20   2100.0
18         NaN       Bruna     20   2100.0
19         NaN     Gabriel     20   2100.0

In [6]:
df.head()

   Unnamed: 0        nome  idade  salário
0         NaN  Paçoquinha     20   1500.0
1         NaN      Paçoca     20   2200.0
2         NaN   Paçoquita     20  10000.0
3         NaN     Bolacha     20   5500.0
4         NaN        Enzo     20   2100.0

In [8]:
df.tail()

    Unnamed: 0     nome  idade  salário
15         NaN    Julia     20   2100.0
16         NaN    Henry     20   2100.0
17         NaN    Harry     20   2100.0
18         NaN    Bruna     20   2100.0
19         NaN  Gabriel     20   2100.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   nome        20 non-null     object
 2   idade       20 non-null     int64
 3   salário     19 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 772.0+ bytes

In [10]:
df.describe()

       Unnamed: 0  idade       salário
count         0.0   20.0     19.000000
mean          NaN   20.0   2668.421053
std           NaN    0.0   1946.521864
min           NaN   20.0   1500.000000
25%           NaN   20.0   2100.000000
50%           NaN   20.0   2100.000000
75%           NaN   20.0   2100.000000
max           NaN   20.0  10000.000000

In [12]:
df.dtypes

Unnamed: 0    float64
nome           object
idade           int64
salário       float64
dtype: object

In [16]:
df.isnull().sum()

Unnamed: 0    20
nome           0
idade          0
salário        1
dtype: int64

In [17]:
df2 = df.dropna()
df2.isnull().sum()

Unnamed: 0    0
nome          0
idade         0
salário       0
dtype: int64

In [21]:
df3 = df
df3['salário'] = df3['salário'].fillna(df['salário'].mean())
df3.isnull().sum()

Unnamed: 0    20
nome           0
idade          0
salário        0
dtype: int64

In [22]:
print(df3)

    Unnamed: 0        nome  idade       salário
0          NaN  Paçoquinha     20   1500.000000
1          NaN      Paçoca     20   2200.000000
2          NaN   Paçoquita     20  10000.000000
3          NaN     Bolacha     20   5500.000000
4          NaN        Enzo     20   2100.000000
5          NaN         Ana     20   2100.000000
6          NaN       Laura     20   2100.000000
7          NaN     Isadora     20   2100.000000
8          NaN        Tony     20   2100.000000
9          NaN       Steve     20   2100.000000
10         NaN      Fulano     20   2100.000000
11         NaN     Ciclano     20   2668.421053
12         NaN  Totezuando     20   2100.000000
13         NaN   Mussarelo     20   2100.000000
14         NaN     Claudio     20   2100.000000
15         NaN       Julia     20   2100.000000
16         NaN       Henry     20   2100.000000
17         NaN       Harry     20   2100.000000
18         NaN       Bruna     20   2100.000000
19         NaN     Gabriel     20   2100.000000